M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue 03 Dec 2024 02:38:18 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-03T14:38:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X6.3262Y-4.8764
X6.5171Y-4.8764
T2
X6.3144Y-4.9957
X6.5289Y-4.9957
M30
